swagger: '2.0'
info:
  title: Argent Bank API Transactions
  version: '1.0.0'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /users:
    get:
      summary: Retrieve all users
      description: Retrieve all users account.
      security:
        - BearerAuth: []
      responses:
        200:
          description: Successfully retrieved all users.
        400:
          description: Unauthorized access to retrieve all users.
        501:
          description: Internal Server Error.

  /users/{user_id}/transactions:
    get:
      summary: Retrieve all transactions of an account
      description: Retrieve all transactions associated with a specific account.
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          description: The ID of the account for which to fetch transactions.
          required: true
          type: integer
      responses:
        200:
          description: Successfully retrieved all transactions.
        400:
          description: Unauthorized access to retrieve all transactions.
        404:
          description: Account not found.
        501:
          description: Internal Server Error.
  /transactions/{transaction_id}/category:
    put:
      summary: Edit a transaction's category
      description: Edit the category of a specific transaction in my API.
      security:
        - BearerAuth: []
      parameters:
        - name: transaction_id
          in: path
          description: The ID of the transaction to edit.
          required: true
          type: integer
        - name: category
          in: body
          description: The new category to assign to the transaction.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Transaction's category edited successfully.
        400:
          description: Unauthorized access to edit the transaction.
        404:
          description: Transaction not found.
        501:
          description: Internal Server Error.
  /transactions/{transaction_id}/note:
    post:
      summary: Add a note to a transaction
      description: Add a note to a specific transaction in my API.
      security:
        - BearerAuth: []
      parameters:
        - name: transaction_id
          in: path
          description: The ID of the transaction to add a note.
          required: true
          type: integer
        - name: note
          in: body
          description: The note to add to the transaction.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Note added to the transaction successfully.
        400:
          description: Unauthorized access to add a note to the transaction.
        404:
          description: Transaction or account not found.
        501:
          description: Internal Server Error.
  /transactions/{transaction_id}/note/{note_id}:
    delete:
      summary: Delete a note of a transaction
      description: Delete a note from a specific transaction in my API.
      security:
        - BearerAuth: []
      parameters:
        - name: transaction_id
          in: path
          description: The ID of the transaction to delete a note from.
          required: true
          type: integer
        - name: note_id
          in: path
          description: The ID of the note you want to delete.
          required: true
          type: integer
      responses:
        200:
          description: Note deleted from the transaction successfully.
        400:
          description: Unauthorized access to delete the note from the transaction.
        404:
          description: Transaction or note not found.
        501:
          description: Internal Server Error.
securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
