swagger: '2.0'
info:
  title: Argent Bank Transactions API
  version: '1.0.0'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /users/{user_id}/transactions:
    get:
      summary: Retrieve all transactions for the current month, grouped by account
      description: Retrieve all transactions for the current month, grouped by account for a specific user.
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          description: The ID of the user to retrieve transactions for.
          required: true
          type: integer
      responses:
        200:
          description: Successfully retrieved all transactions.
        400:
          description: Unauthorized access to retrieve transactions.
        404:
          description: User not found.
        501:
          description: Internal Server Error.

  /users/{user_id}/transactions/{transaction_id}:
    get:
      summary: Retrieve details of a specific transaction
      description: Retrieve details of a specific transaction for a specific user.
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          description: The ID of the user.
          required: true
          type: integer
        - name: transaction_id
          in: path
          description: The ID of the transaction to retrieve details.
          required: true
          type: integer
      responses:
        200:
          description: Successfully retrieved transaction details.
        400:
          description: Unauthorized access to retrieve transaction details.
        404:
          description: User or transaction not found.
        501:
          description: Internal Server Error.

    put:
      summary: Update information on a specific transaction
      description: Update information on a specific transaction for a specific user.
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          description: The ID of the user.
          required: true
          type: integer
        - name: transaction_id
          in: path
          description: The ID of the transaction to update.
          required: true
          type: integer
        - name: update_data
          in: body
          description: The data to update for the transaction.
          required: true
          schema:
            type: object
            properties:
              field1:
                type: string
              field2:
                type: integer
              # Add more fields as needed
      responses:
        200:
          description: Transaction information updated successfully.
        400:
          description: Unauthorized access to update transaction information.
        404:
          description: User or transaction not found.
        501:
          description: Internal Server Error.

    delete:
      summary: Delete a specific transaction
      description: Delete a specific transaction for a specific user.
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          description: The ID of the user.
          required: true
          type: integer
        - name: transaction_id
          in: path
          description: The ID of the transaction to delete.
          required: true
          type: integer
      responses:
        200:
          description: Transaction deleted successfully.
        400:
          description: Unauthorized access to delete transaction.
        404:
          description: User or transaction not found.
        501:
          description: Internal Server Error.

securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
